export const ALL_GAMES = [
  { id: 'arithmetic',           name: 'Number Ninja',          emoji: '🎯', xp: 50,  path: '/games/arithmetic' },
  { id: 'number-catcher',       name: 'Number Catcher',        emoji: '🥥', xp: 40,  path: '/games/number-catcher' },
  { id: 'balloon-pop',          name: 'Balloon Pop',           emoji: '🎈', xp: 45,  path: '/games/balloon-pop' },
  { id: 'geometry',             name: 'Shape Explorer',        emoji: '📐', xp: 60,  path: '/games/geometry' },
  { id: 'meteor',               name: 'Multiplication Meteor', emoji: '☄️', xp: 75,  path: '/games/meteor' },
  { id: 'fractions',            name: 'Fraction Frenzy',       emoji: '🍕', xp: 50,  path: '/games/fractions' },
  { id: 'farm-multiply',        name: 'Multiplication Farm',   emoji: '🌻', xp: 65,  path: '/games/farm-multiply' },
  { id: 'math-racing',          name: 'Math Racing',           emoji: '🐂', xp: 70,  path: '/games/math-racing' },
  { id: 'balancer',             name: 'Equation Balancer',     emoji: '⚖️', xp: 75,  path: '/games/balancer' },
  { id: 'decimal-mall',         name: 'Decimal Mall',          emoji: '🛒', xp: 80,  path: '/games/decimal-mall' },
  { id: 'fraction-ninja',       name: 'Fraction Ninja',        emoji: '🥷', xp: 85,  path: '/games/fraction-ninja' },
  { id: 'patterns',             name: 'Pattern Puzzle',        emoji: '🧩', xp: 80,  path: '/games/patterns' },
  { id: 'coordinate-treasure',  name: 'Treasure Map',          emoji: '🗺️', xp: 90,  path: '/games/coordinate-treasure' },
  { id: 'integer-mountain',     name: 'Integer Mountain',      emoji: '🏔️', xp: 100, path: '/games/integer-mountain' },
  { id: 'algebra-dungeon',      name: 'Algebra Dungeon',       emoji: '🗝️', xp: 110, path: '/games/algebra-dungeon' },
  { id: 'fraction-slicer',      name: 'Fraction Slicer',       emoji: '🍕', xp: 70,  path: '/games/fraction-slicer' },
  { id: 'number-sort-rush',     name: 'Number Sort Rush',      emoji: '🗂️', xp: 65,  path: '/games/number-sort-rush' },
  { id: 'math-mole',            name: 'Math Mole',             emoji: '🔨', xp: 80,  path: '/games/math-mole' },
];

export const GAME_ID_TO_NAME = Object.fromEntries(ALL_GAMES.map(g => [g.id, g.name]));

export const GAME_TOPIC_MAP = {
  'arithmetic':          'Arithmetic',
  'number-catcher':      'Arithmetic',
  'balloon-pop':         'Arithmetic',
  'geometry':            'Geometry',
  'meteor':              'Arithmetic',
  'fractions':           'Fractions',
  'farm-multiply':       'Arithmetic',
  'math-racing':         'Arithmetic',
  'balancer':            'Algebra',
  'decimal-mall':        'Decimals',
  'fraction-ninja':      'Fractions',
  'patterns':            'Patterns',
  'coordinate-treasure': 'Geometry',
  'integer-mountain':    'Arithmetic',
  'algebra-dungeon':     'Algebra',
  'fraction-slicer':    'Fractions',
  'number-sort-rush':   'Patterns',
  'math-mole':          'Arithmetic',
};
